---
- name: Configurar servidor web
  hosts: web
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Iniciar y habilitar el servicio Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copiar archivos HTML al directorio de Apache
      copy:
        src: ./html/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'
